### ISSUE TITLE
List Ordering Mixup

### ISSUE THREAD

**Issue by PickleWeaselPhD** [andrewbrey/netflix-tweaked#1]
**Describe the bug**
Instead of list order being Continue Watching, My List, then everything else, the page loads with My List at the top, which is quickly replaced with Continue Watching, then everything else is listed, then My List is placed at the bottom or second from the bottom.

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Browser: Chrome
 - Version: 67.0.3396.99 (Official Build) (64-bit)

**Additional context**
All other aspects are working as expected.
I have other extensions installed, but they are disabled for Netflix.
 - Stylish (no overrides loaded or enabled)
 - Tampermonkey (no scripts loaded or enabled)
 - uBlock Origin (disabled for all of Netflix)

**Comment by andrewbrey** [comment]
Does this happen consistently? When you reload the page, does it sometimes sort correctly and other times not? It would be curious if it's consistent, and if it's intermittent, I think it'll be related to the race condition I'm already aware of where the extension code sometimes executes too quickly for Netflix and so Netflix's "wins out".

**Comment by PickleWeaselPhD** [comment]
I just noticed that it only does it on a fresh load of the site. If I click any of the header links, then return to the home page, it will correctly order the lists Continue, My List, then everything else.

**Comment by andrewbrey** [comment]
Ok, thanks for the report. I'll take a look into reproducing and fixing this when I make the next round of updates.

**Comment by andrewbrey** [comment]
This should be fixed by 9431624829077ec6a641565c66a4565ab9e880ec. @PickleWeaselPhD, care to give it a few tries to confirm? You may need to restart Chrome to have it pick up the updated extension (or you can manually trigger an update by going to `chrome://extensions -> Update`.

**Comment by andrewbrey** [comment]
@PickleWeaselPhD Would you mind also confirming that you have the v1.0.2 extension installed and enabled? The specific behavior you're reporting hasn't been reported by anyone else and it's super strange. Out of curiosity, what region are you in? I wonder if there's something Netflix serves up differently for where you live vs where I am (Denver, CO).

**Comment by PickleWeaselPhD** [comment]
The installed version is indeed 1.0.2 and it is enabled. I'm in FL, so I don't believe it would be a region issue. I checked the dev console and I'm not getting errors, and the CSS tweaks are loaded for sure, but I still have a differing first load than what is expected.

The My List group is being forced to the bottom of the stack as new groups are loaded between it and the Continue Watching group. Once I have scrolled all the way to the bottom of the page and all categories are served to my browser, clicking any of the headers will sort the lists correctly, but only after the initial page load.

**Comment by andrewbrey** [comment]
@PickleWeaselPhD Ok, I've just pushed a new version (1.0.3) that...should?...address this :)

Give it a shot and let me know - just make sure you update the extension and also make sure that you refresh your Netflix tab to ensure the latest code is loaded into the page.

**Comment by andrewbrey** [comment]
Since this was reported as being squashed, I'm closing this issue. If it is experienced again, we can reopen and explore further fixes at that time.

**Comment by PickleWeaselPhD** [comment]
This 100% fixed the issue. I am now seeing things in the correct order.

Thanks again for your work! It is super appreciated.
